name: npm_publish
on: [push]
# on:
#   release:
#     types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - run: npm init --scope=nosto -y
      - run: npm install
      - run: npm run build
      - uses: JS-DevTools/npm-publish@v1
        with:
          # token: ${{ secrets.NPMJS_TOKEN }}
          token: "wrong-value"
          access: "public"
          dry-run: true
          check-version: true